# Generated by Django 3.2 on 2022-07-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_userprofile_users_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='users_wishlist',
        ),
    ]
