# Generated by Django 3.2 on 2022-05-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_checkout_order_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
