# Generated by Django 3.2 on 2022-04-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220419_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trainer_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
