# Generated by Django 3.2 on 2022-06-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_reviews',
        ),
    ]
