# Generated by Django 3.2 on 2022-06-15 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productreviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreviews',
            options={'verbose_name_plural': 'Product Reviews'},
        ),
    ]
