# Generated by Django 3.2 on 2022-07-01 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='users_wishlist',
        ),
    ]
